# Generated by Django 6.1 on 2026-10-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('ip_hash', models.CharField(max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['visited_at', 'is_bot'], name='core_pagevi_visited_dcbaa2_idx'), models.Index(fields=['path', 'visited_at'], name='core_pagevi_path_ca419b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteStats',
            fields=[
            ],
            options={
                'verbose_name': 'Visitor Stats',
                'verbose_name_plural': '📊 Visitor Stats',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pagevisit',),
        ),
    ]
