# Generated by Django 6.1 on 2026-10-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pagevisit_sitestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='lifetime_bot_visits',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='lifetime_human_visits',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
