# Generated by Django 6.1 on 2026-08-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_video_youtube_id_bandcampembed_youtube_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandcampembed',
            name='bandcamp_url',
            field=models.CharField(blank=True, help_text='Paste the Bandcamp album or track URL — embed code is fetched automatically', max_length=500),
        ),
        migrations.AlterField(
            model_name='bandcampembed',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Auto-populated from Bandcamp URL. Override here if needed.'),
        ),
        migrations.AlterField(
            model_name='bandcampembed',
            name='youtube_url',
            field=models.CharField(blank=True, help_text='YouTube URL — alternative to Bandcamp', max_length=200),
        ),
    ]
