# Generated by Django 6.1 on 2026-10-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_bandcampembed_bandcamp_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Optional MP3/audio file displayed as a player on this page', null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload an MP4/WebM video file (alternative to YouTube URL)', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.CharField(blank=True, default='', help_text='Paste the full YouTube URL, e.g. https://www.youtube.com/watch?v=…', max_length=200),
        ),
    ]
