# Generated by Django 6.1 on 2026-08-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bandcamp_embed_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='bandcamp_url',
            field=models.CharField(blank=True, help_text='Optional: paste a Bandcamp album or track URL to embed audio', max_length=500),
        ),
    ]
