# Generated by Django 6.1 on 2026-10-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_bandcamp_embed_html_post_bandcamp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Optional MP3/audio file displayed as a player in this post', null=True, upload_to='audio/'),
        ),
    ]
